<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}
	
	acf_add_local_field_group( array(
		'key' => 'group_65540963d68f5',
		'title' => 'Order Form Block',
		'fields' => array(
			array(
				'key' => 'field_65540964f03de',
				'label' => 'Order Form',
				'name' => 'form_id',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'' => NULL,
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_65541313411cc',
				'label' => '',
				'name' => 'show_title',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show form title',
				'default_value' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'zm-order-forms/order-form',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
	
	acf_add_local_field_group( array(
		'key' => 'group_6553f2c50e782',
		'title' => 'Order Forms',
		'fields' => array(
			array(
				'key' => 'field_655539c65ee02',
				'label' => 'Locations',
				'name' => 'order_form_locations',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => 'Optional. Used to create a dropdown on every order form.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => 4,
				'placeholder' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6553f2c521415',
				'label' => 'Order Forms',
				'name' => 'order_forms',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 1,
				'max' => 0,
				'collapsed' => 'field_6553f8d3ac610',
				'button_label' => 'Add Order Form',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_6553f8d3ac610',
						'label' => 'Form Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6553f2c521415',
					),
					array(
						'key' => 'field_6553fd2c43771',
						'label' => 'Form ID',
						'name' => 'id',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'The form ID is used to embed the form using the following shortcode:<br><code class="code zmof-form-shortcode">[zm_order_form id="Your ID"]</code>',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6553f2c521415',
					),
					array(
						'key' => 'field_6553f8f5ac611',
						'label' => 'Recipient Emails',
						'name' => 'to',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Separate emails with a comma to send to multiple recipients.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6553f2c521415',
					),
					array(
						'key' => 'field_6553f92dac612',
						'label' => 'Categories',
						'name' => 'categories',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'min' => 1,
						'max' => 0,
						'collapsed' => 'field_6553f93aac613',
						'button_label' => 'Add Category',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_6553f93aac613',
								'label' => 'Category Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_6553f92dac612',
							),
							array(
								'key' => 'field_6553f947ac614',
								'label' => 'Products',
								'name' => 'products',
								'aria-label' => '',
								'type' => 'textarea',
								'instructions' => 'Enter one product per line',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'rows' => 6,
								'placeholder' => '',
								'new_lines' => '',
								'parent_repeater' => 'field_6553f92dac612',
							),
						),
						'parent_repeater' => 'field_6553f2c521415',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'zmof-settings',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

